accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
]

articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='list'),
    path('create/', views.create, name='create'),
    path('<str:slug>/', views.article_detail, name='detail'),
]

netninja_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from articles.views import article_list


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', article_list, name='article_list'),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    thumbnail = models.ImageField()
    # author

    def __str__(self):
        return self.title
    
    def snippet(self):
        if len(self.body) > 50:
            return self.body[:50] + ' .....'
        else:
            return self.body

articles/forms.py
from django.forms import ModelForm
from .models import Article


class ArticleCreateForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'slug', 'body']

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})

class UserLoginView(LoginView):
    template_name = 'accounts/login.html'

class UserLogoutView(LogoutView):
    template_name = 'accounts/logout.html'

articles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Article
from .forms import ArticleCreateForm


def article_list(request):
    articles = Article.objects.all().order_by('-date')
    return render(request, 'articles/article_list.html', {'articles':articles})

def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article':article})

@login_required
def create(request):
    if request.method ==  'POST':
        form = ArticleCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:list')
    else:
        form = ArticleCreateForm()
    return render(request, 'articles/article_create.html', {'form':form})

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}
<p>You have successfully logout. <a href="{% url 'accounts:login' %}">Login again</a></p>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">SignUp</button>
    </form>
</div>
{% endblock %}

templates/articles/article_create.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Create</button>
    </form>
{% endblock %}

templates/articles/article_detail.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'articles:list' %}">View all articles</a>

<div class="py-3">
    <h1 class="font-bold text-3xl">{{ article.title }}</h1>
    <p class="font-semibold">{{ article.date }}</p>
</div>

<div class="flex justify-center">
    <img class="h-72" src="{{ article.thumbnail.url }}" alt="">
</div>
<p class="pt-3 text-justify font-medium text-base">{{ article.body }}</p>
{% endblock %}

templates/articles/article_list.html
{% extends 'base.html' %}

{% block content %}
<div class="md:grid grid-cols-3 gap-6">
    {% for article in articles %}
    <div class="mb-6 md:mb-0 border rounded bg-white">
        <a href="{% url 'articles:detail' article.slug %}">
            <img class="h-64 w-full" src="{{ article.thumbnail.url }}" alt="">
            <div class="p-3">
                <h2 class="font-bold text-xl">{{ article.title }}
                </h2>
                <!-- <p class="font-normal text-base">{{ article.snippet }}</p> -->
                <p class="font-medium text-base">{{ article.date.date }}</p>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NetNinja || Articles, Blog, News etc.</title>
    <link rel="stylesheet" href="{% static 'css/flowbite.min.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/styles.css' %}"> -->
    <!-- <link rel="stylesheet" href="{% static 'js/tailwind-css.js' %}"> -->
</head>

<body class="bg-gray-50 text-gray-900">
    <div class="container p-5 mx-auto flex items-center justify-between">
        <h1 class="text-2xl font-bold"><a href="{% url 'article_list' %}">NETNINJA</a></h1>

        <ul class="text-base">
            {% if user.is_authenticated %}
            <li class="pr-4"><a href="{% url 'accounts:logout' %}">Logout</a></li>
            {% else %}
            <span class="flex">
                <li class="pr-4"><a href="{% url 'accounts:login' %}">Login</a></li>
                <li class="pr-4"><a href="{% url 'accounts:signup' %}">SignUp</a></li>
            </span>
            {% endif %}
        </ul>
    </div>
    
    <div class="container px-5 mx-auto">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>